volumes:
  jwtdown-db-data:
    external: true
  mongo-data:
    external: true
services:
  fastapi:
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
    environment:
      MONGO_URL: mongodb://admin:password@mongo
      SIGNING_KEY: ${SIGNING_KEY}
  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  # mongo-express:
  #   image: mongo-express:latest
  #   depends_on:
  #     - mongo
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: password
  #     ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/
  #   restart: always
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000
